version: '3.9'
services:
  app:
    image: suture-backend
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: suturedb
    networks:
      - app-network

networks:
  app-network:
