version: '3.8'

services:
  suture-backend:
    image: suture-backend
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: suturedb
    ports:
      - "5432:5432"
