services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data 

  app:
    build:
      context: ../.
    container_name: psycopg_app
    environment:
      DB_HOST: db
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  db_data: 
