name: Feature CI/CD

on:
  push:
    branches:
      - feature-*

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Images
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: |
            ghcr.io/dreamteamse/sutureservice-arduino-manager:dev
            ghcr.io/dreamteamse/sutureservice-backend:dev
            ghcr.io/dreamteamse/sutureservice-frontend:dev
          context: .
          file: |
            ./arduino_manager/Dockerfile
            ./backend/Dockerfile
            ./frontend/Dockerfile

  push:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    needs: build

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Images
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/dreamteamse/sutureservice-arduino-manager:dev
            ghcr.io/dreamteamse/sutureservice-backend:dev
            ghcr.io/dreamteamse/sutureservice-frontend:dev
          context: .
          file: |
            ./arduino_manager/Dockerfile
            ./backend/Dockerfile
            ./frontend/Dockerfile
