name: Feature CI/CD

on:
  push:
    branches:
      - feature-*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and Push Images
        run: |
            docker build -t ghcr.io/dreamteamse/sutureservice-arduino-manager:dev ../arduino_manager/.
            docker build -t ghcr.io/dreamteamse/sutureservice-backend:dev ../backend/.
            docker build -t ghcr.io/dreamteamse/sutureservice-frontend:dev ../frontend/.

            docker push ghcr.io/dreamteamse/sutureservice-arduino-manager:dev
            docker push ghcr.io/dreamteamse/sutureservice-backend:dev
            docker push ghcr.io/dreamteamse/sutureservice-frontend:dev

