name: Production Build

on:
  pull_request:
    branches:
      - staging

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Hello World
      run: echo "Hello, World!"
