name: Staging CI/CD

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker Images
        run: |
          docker build -t ghcr.io/dreamteamse/sutureservice-arduino-manager:staging ./arduino_manager/.
          docker build -t ghcr.io/dreamteamse/sutureservice-backend:staging ./backend/.
          docker build -t ghcr.io/dreamteamse/sutureservice-frontend:staging ./frontend/.

  push:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    needs: build

    steps:
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Push Docker Images
        run: |
          docker push ghcr.io/dreamteamse/sutureservice-arduino-manager:staging
          docker push ghcr.io/dreamteamse/sutureservice-backend:staging
          docker push ghcr.io/dreamteamse/sutureservice-frontend:staging